package com.example.simplelife.data

import com.google.firebase.database.FirebaseDatabase
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.launch

class SimpleLifeRepository(private val db: AppDatabase) {

    // 1. Initialize Firebase with YOUR URL
    private val firebaseDb = FirebaseDatabase.getInstance("https://simplelife-c54be-default-rtdb.firebaseio.com")

    // 2. Create references to where we want to store data
    private val expensesRef = firebaseDb.getReference("expenses")
    private val habitsRef = firebaseDb.getReference("habits")
    private val moodsRef = firebaseDb.getReference("moods")

    // --- EXPENSES ---
    val allExpenses: Flow<List<Expense>> = db.expenseDao().getAllExpenses()
    val totalSpending: Flow<Double?> = db.expenseDao().getTotalSpending()

    suspend fun addExpense(expense: Expense) {
        // A. Save Locally (Room)
        db.expenseDao().insertExpense(expense)

        // B. Save to Cloud (Firebase)
        // We use .push() to generate a unique key for the cloud entry
        CoroutineScope(Dispatchers.IO).launch {
            expensesRef.push().setValue(expense)
        }
    }

    suspend fun deleteExpense(expense: Expense) {
        db.expenseDao().deleteExpense(expense)
        // Note: Deleting from Firebase by 'value' is harder without a unique ID key.
        // For this simplified app, we focus on BACKING UP data to the cloud.
    }

    // --- HABITS ---
    fun getHabitsForDate(date: Long): Flow<List<Habit>> {
        return db.habitDao().getHabitsByDate(date)
    }

    suspend fun addHabit(habit: Habit) {
        // A. Local
        db.habitDao().insertHabit(habit)

        // B. Cloud
        CoroutineScope(Dispatchers.IO).launch {
            habitsRef.push().setValue(habit)
        }
    }

    suspend fun updateHabitStatus(id: Int, isCompleted: Boolean) {
        db.habitDao().updateHabitStatus(id, isCompleted)
        // Syncing updates to Firebase is complex for a starter app
        // because we need to find the exact Key generated by .push().
        // We will skip updating cloud status for now to keep it simple.
    }

    suspend fun deleteHabit(habit: Habit) {
        db.habitDao().deleteHabit(habit)
    }

    // --- MOODS ---
    val allMoods: Flow<List<MoodEntry>> = db.moodDao().getAllMoods()

    suspend fun addMood(mood: MoodEntry) {
        db.moodDao().insertMood(mood)

        // B. Cloud
        CoroutineScope(Dispatchers.IO).launch {
            moodsRef.push().setValue(mood)
        }
    }
}